### ISSUE TITLE
Failing to compile on iOS

### ISSUE THREAD

**Issue by sarangborude** [atteneder/DracoUnity#10]
When I tried to build for iOS, I got this error

ld: warning: ignoring file /Users/boruds/Dev/Unity/ARPrototypingFrameworkUnity/iOS_Build/Libraries/com.atteneder.draco/Runtime/Plugins/iOS/libdracodec_unity.a, building for iOS-arm64 but attempting to link with file built for unknown-unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F )
Undefined symbols for architecture arm64:
  "_ReleaseUnityMesh", referenced from:
      _DracoMeshLoader_ReleaseUnityMesh_m72BB9F8160DEC79261D38EDAEB7E42F70FE098B7 in Draco.o
      _DracoMeshLoader_CreateMesh_m44D511377C2503325075CAA7F2FC656563C72141 in Draco.o
     (maybe you meant: _DracoMeshLoader_ReleaseUnityMesh_m72BB9F8160DEC79261D38EDAEB7E42F70FE098B7)
  "_DecodeMeshForUnity", referenced from:
      _DracoMeshLoader_DecodeMeshForUnity_mC7E4030CBE9C1311B512573267439294210899E0 in Draco.o
      _DracoJob_Execute_m42329B186729FCDC589207402D0A99A9AA978D65 in Draco.o
     (maybe you meant: _DracoMeshLoader_DecodeMeshForUnity_mC7E4030CBE9C1311B512573267439294210899E0)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sarangborude** [comment]
Seems like on building, Unity doesn't put out a .a file for arm.

**Comment by atteneder** [comment]
in short:
DracoUnity uses a GIT extension called [GIT LFS](https://git-lfs.github.com/) (large file support). If you install DracoUnity via GIT, you have to install and use GIT LFS, otherwise certain binary files (like the .a library your error mentions) are not downloaded correctly.

You can find this in the [README under *Installation*](https://github.com/atteneder/DracoUnity#installing), hidden behind `Alternative: Install via GIT URL`.

In case you want to learn how to spot this (or how I figured it out):

If a file from a GIT repository that's supposed to be bigger is just around 130 bytes in size, try opening it with an editor. It probably starts with a `version` and a link to a git lfs version (in fact the hex codes in your error message reveal that as well). That's an indicator you need to install GIT LFS and perform
`git lfs pull` on your clone.

hth

**Comment by sarangborude** [comment]
Thanks, this is such a huge help!!!
