### ISSUE TITLE
Doc + Demo + dll problem + point cloud

### ISSUE THREAD

**Issue by vince958** [atteneder/DracoUnity#14]
Hello,

I'm a little bit confused, I found out that the repository and package manager versions are totally different. The Demo project is not containing example for me so with precious version it was pretty simple to use code but now it's a little bit more difficult and the dracodec_unity.dll and dracoenc_unity.dll are broken ("Failed to load 'Assets/DracoUnity/Runtime/Plugins/x86_64/dracoenc_unity.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.")

I was using the previous version without problem but now I have to read point clouds and I don't know How to do it... Can you bring me some help on that Subjects?

Thanks you, Vincent

**Comment by atteneder** [comment]
Hi,

Can you please structure your report (ideally one issue per problem, but at least use paragraphs) and be more specific? "A bit more difficult to use" leaves me in the dark wrt what your actual problem is.

The main branch is a development branch and a 2.x preview version with some remaining issues (hence it's not released yet).

Did you, by chance,  not fetch the GIT LFS files (the DLLs are GIT LFS)?
