### ISSUE TITLE
[Question] v4.0.0 required Unity version

### ISSUE THREAD

**Issue by camnewnham** [atteneder/DracoUnity#25]
Hi @atteneder, just a quick query:
The notes for the v4 preview list Unity 2021 as minimum required - is this for WebGL only or for the entire library?
https://github.com/atteneder/DracoUnity/releases/tag/v4.0.0-preview.2

Cheers
Cam

**Comment by atteneder** [comment]
Hi @camnewnham ,

Well spotted! And you're right! The only change that breaks compatibility is the WebGL native libs are built with a newer Emscripten now (to match Unity's version). Otherwise 4.0.0 has the same feature set as 3.0.0. Although this is additional work for maintenance, I just don't see another way of making this work out-of-the box for users.

I plan to back port changes to 3.x for a reasonable long time though.

Regards
