### ISSUE TITLE
DracoEncode.cs not visible

### ISSUE THREAD

**Issue by MoritzSkowronski** [atteneder/DracoUnity#37]
The static class public static class `DracoEncode` or its methods like `EncodeMesh` are not accessible.

This is on Unity 202.3.22f1 with Draco 4.0.1

**Comment by atteneder** [comment]
Hi @MoritzSkowronski ,

That seems wrong indeed, I'll have a look hopefully next week.

What do you want to do with it? Fyi: If it's runtime compression, I've not tested if it works yet.

**Comment by MoritzSkowronski** [comment]
My goal, although this is not possible yet, I presume, is to compress and decompress a LIDAR scanned point cloud to sent over WIFI.

**Comment by atteneder** [comment]
@MoritzSkowronski Makes sense. Runtime compression (once it's implemented) will probably take some time (depending on data size, ofc).

**Comment by AR-Vsx** [comment]
I'm currently facing the same issue. Are there any updates ?

**Comment by atteneder** [comment]
@AR-Vsx No updates so far. It's not a priority on my side, but I'm happy to review contributions if someone wants to tackle it sooner.

**Comment by AR-Vsx** [comment]
I was able to use the namespace by creating a Assembly Definiton File in my Scripts folder and referencing both Draco and DracoEncoder.

**Comment by atteneder** [comment]
Revising this after some time:

`Draco.Encoder.DracoEncoder` is a public class, so that's not the problem. The assembly definition it is part of (`DracoEncoder`) is not auto-referenced though. That means if you want to use it, create your own assembly definition and reference it explicitly ([more on asmdefs](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html)).

That should fix the original problem, thus I'm closing this issue.

Now regarding the greater picture feature - Runtime Export:
There's now a dedicated issue in #56 .
Have you been able to get it running? Could you report your experience? What platforms are you running it on? 

Thanks
