### ISSUE TITLE
Encoding/decoding produces a mirrored mesh

### ISSUE THREAD

**Issue by Daniel4144** [atteneder/DracoUnity#42]
Encoding or decoding a mesh mirrors the mesh along the x-axis, I could not determine which one flips the coordinates.
The following sample code encodes and decodes a single triangle and displays the mesh before and after, they should be equal:

  ```csharp
        Mesh mesh1 = new Mesh();
        mesh1.vertices = new Vector3[] { Vector3.right, Vector3.up, Vector3.forward };
        mesh1.triangles = new int[] { 0, 1, 2 };
        EncodeResult[] result = DracoEncoder.EncodeMesh(mesh1);

        Mesh mesh2 = await new DracoMeshLoader().ConvertDracoMeshToUnity(result[0].data);

        GameObject obj1 = new GameObject("before");
        obj1.AddComponent<MeshFilter>().sharedMesh = mesh1;

        GameObject obj2 = new GameObject("after");
        obj2.AddComponent<MeshFilter>().sharedMesh = mesh2;

        obj1.AddComponent<MeshRenderer>().sharedMaterial = new Material(Shader.Find("Standard"));
        obj2.AddComponent<MeshRenderer>().sharedMaterial = new Material(Shader.Find("Standard"));
```

The same happens for all meshes, not only in this sample with a single triangle.

DracoUnity version 4.0.2
Unity version version 2020.3.30f1

**Comment by atteneder** [comment]
@Daniel4144 thanks for reporting!

You're right, that's problematic indeed. Draco itself does not define coordinate space handedness whatsoever, but DracoUnity is most often used in a glTF context, where a coordinate system conversion happens upon decoding.

I need to have a closer look where exactly this happens.

Two solutions come to mind:

- Do the same space conversion on both encode and decode, so that round-trips are possible and work with glTFs
- Make the space conversions optional via parameter for generic usage

The latter seems more sound to me

**Comment by atteneder** [comment]
@Daniel4144 I had a close look. Space conversion already is an option for `DracoMeshLoader`:

```csharp
public DracoMeshLoader(bool convertSpace = true) {
    this.convertSpace = convertSpace;
}
```

So in your example, try:

```csharp
Mesh mesh2 = await new DracoMeshLoader(false).ConvertDracoMeshToUnity(result[0].data);
```

An option for encoding is still missing, but will be required for glTF export.

**Comment by Daniel4144** [comment]
Thanks @atteneder for the help. I have missed that option, but that should work.
I am using DracoUnity to save generated colliders and load them later and as a workaround I have scaled all colliders with -1 after loading, but the builtin option is way better.
