### ISSUE TITLE
Unknown Architecture Error

### ISSUE THREAD

**Issue by MrGadget1024** [atteneder/DracoUnity#54]
Win 11 / WebGL / Unity 2021.3.9 and 2021.3.15

![image](https://user-images.githubusercontent.com/9826063/206032449-6aa43b1a-0e70-4787-bd39-a7c38b619001.png)

![image](https://user-images.githubusercontent.com/9826063/206032141-c97b4a3e-0de4-46c9-a374-d9f043130945.png)

**Comment by atteneder** [comment]
Hi,

chances are that instead of installing DracoUnity via the [OpenUPM package installer](https://package-installer.glitch.me/v1/installer/OpenUPM/com.atteneder.draco?registry=https%3A%2F%2Fpackage.openupm.com&scope=com.atteneder) which is recommended in the README.md  you cloned the repository and forgot to pull the GIT LFS files.
It could be that GIT blocked you from cloning the LFS files, since I'm constantly running out of quota for it recently and so installing via installer is the most reliable (and absolutely sufficient if you don't plan to develop DracoUnity).
